DROP TABLE IF EXISTS customers cascade;
DROP TABLE IF EXISTS products cascade;
DROP TABLE IF EXISTS categories cascade;
DROP TABLE IF EXISTS order_information cascade;

CREATE TABLE customers (
  id           integer generated by default as identity PRIMARY KEY,
  first_name   varchar(20) NOT NULL,
  last_name    varchar(20) NOT NULL,
  city         varchar(50) NOT NULL,
  email        varchar(50) NOT NULL
);  

CREATE TABLE categories (
  id              integer generated by default as identity PRIMARY KEY,
  name            varchar(50) NOT NULL,
  discount        integer,
  available       BOOLEAN,
  clearance       BOOLEAN
);

CREATE TABLE products (
  id            integer generated by default as identity PRIMARY KEY,
  name          varchar(50) NOT NULL,
  price         integer NOT NULL,
  manufacturer  varchar(70) NOT NULL,
  categories_id integer references categories(id)
);

CREATE TABLE order_information (
  id            integer generated by default as identity PRIMARY KEY,
  date_placed   date NOT NULL,
  customers_id  integer references customers(id),
  categories_id integer references categories(id),
  products_id   integer references products(id),
  total_cost    float
);

